# Generated by Django 5.2.5 on 2025-08-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('assessment_type', models.CharField(choices=[('academic', 'Academic Assessment'), ('psychological', 'Psychological Assessment'), ('physical', 'Physical Assessment'), ('career', 'Career Assessment'), ('dmit', 'DMIT Assessment')], max_length=20)),
                ('curriculum', models.CharField(blank=True, choices=[('CBSE', 'CBSE'), ('ICSE', 'ICSE'), ('IGCSE', 'IGCSE'), ('IB', 'International Baccalaureate')], max_length=10, null=True)),
                ('grade', models.CharField(max_length=10)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('duration_minutes', models.IntegerField(default=60)),
                ('passing_score', models.DecimalField(decimal_places=2, default=40.0, max_digits=5)),
                ('max_score', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'assessments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_questions', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('time_taken_minutes', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('wellbeing_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fitness_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('career_readiness_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('responses', models.JSONField(blank=True, default=dict)),
                ('analysis_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'assessment_results',
                'ordering': ['-completed_at', '-started_at'],
            },
        ),
    ]
