# Generated by Django 5.2.5 on 2025-08-29 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_score', models.FloatField(blank=True, null=True)),
                ('psychological_score', models.FloatField(blank=True, null=True)),
                ('physical_score', models.FloatField(blank=True, null=True)),
                ('overall_score', models.FloatField(blank=True, null=True)),
                ('performance_trend', models.JSONField(default=dict)),
                ('strength_areas', models.JSONField(default=list)),
                ('improvement_areas', models.JSONField(default=list)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_performance', models.JSONField(default=dict)),
                ('confidence_scores', models.JSONField(default=dict)),
                ('future_trends', models.JSONField(default=dict)),
                ('risk_factors', models.JSONField(default=list)),
                ('success_indicators', models.JSONField(default=list)),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parent_dashboard.assessmentcalculation')),
            ],
        ),
        migrations.CreateModel(
            name='CareerMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_careers', models.JSONField(default=list)),
                ('career_match_scores', models.JSONField(default=dict)),
                ('skill_gaps', models.JSONField(default=list)),
                ('development_path', models.JSONField(default=dict)),
                ('industry_trends', models.JSONField(default=dict)),
                ('education_requirements', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prediction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parent_dashboard.predictionresult')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('academic', 'Academic'), ('psychological', 'Psychological'), ('physical', 'Physical'), ('career', 'Career'), ('study_method', 'Study Method'), ('extracurricular', 'Extracurricular')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('high', 'High Priority'), ('medium', 'Medium Priority'), ('low', 'Low Priority')], max_length=10)),
                ('actionable_steps', models.JSONField(default=list)),
                ('expected_outcome', models.TextField()),
                ('timeline', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parent_dashboard.predictionresult')),
            ],
            options={
                'ordering': ['priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParentFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('helpful', 'Helpful'), ('not_helpful', 'Not Helpful'), ('partially_helpful', 'Partially Helpful'), ('inaccurate', 'Inaccurate')], max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('prediction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parent_dashboard.predictionresult')),
                ('recommendation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parent_dashboard.recommendation')),
            ],
        ),
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_type', models.CharField(choices=[('excel', 'Excel File'), ('csv', 'CSV File'), ('image', 'Image/Document'), ('manual', 'Manual Entry')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Upload'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='parent_uploads/')),
                ('detected_curriculum', models.CharField(blank=True, max_length=100, null=True)),
                ('detected_semester', models.CharField(blank=True, max_length=50, null=True)),
                ('detected_year', models.CharField(blank=True, max_length=50, null=True)),
                ('detected_subjects', models.JSONField(default=list)),
                ('raw_data', models.JSONField(default=dict)),
                ('processed_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='assessmentcalculation',
            name='upload_session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parent_dashboard.uploadsession'),
        ),
    ]
