# Generated by Django 5.2.5 on 2025-08-24 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('alert', 'Alert')], default='info', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, max_length=255, null=True)),
                ('action_text', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dashboard_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(default='default', max_length=50)),
                ('language', models.CharField(default='en', max_length=10)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=50)),
                ('auto_refresh', models.BooleanField(default=True)),
                ('refresh_interval', models.IntegerField(default=300)),
                ('show_notifications', models.BooleanField(default=True)),
                ('show_quick_actions', models.BooleanField(default=True)),
                ('default_chart_type', models.CharField(default='line', max_length=20)),
                ('chart_animations', models.BooleanField(default=True)),
                ('chart_colors', models.JSONField(default=list)),
                ('default_export_format', models.CharField(default='pdf', max_length=10)),
                ('include_charts_in_exports', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dashboard_settings',
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('widget_type', models.CharField(choices=[('stat_card', 'Statistics Card'), ('chart', 'Chart'), ('table', 'Data Table'), ('progress', 'Progress Bar'), ('alert', 'Alert/Notification'), ('quick_action', 'Quick Action')], max_length=20)),
                ('chart_type', models.CharField(blank=True, choices=[('line', 'Line Chart'), ('bar', 'Bar Chart'), ('pie', 'Pie Chart'), ('doughnut', 'Doughnut Chart'), ('radar', 'Radar Chart'), ('scatter', 'Scatter Plot')], max_length=20, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('config', models.JSONField(default=dict)),
                ('data_source', models.CharField(max_length=100)),
                ('refresh_interval', models.IntegerField(default=300)),
                ('position_x', models.IntegerField(default=0)),
                ('position_y', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=4)),
                ('height', models.IntegerField(default=3)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_resizable', models.BooleanField(default=True)),
                ('is_draggable', models.BooleanField(default=True)),
                ('allowed_roles', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dashboard_widgets',
                'ordering': ['position_y', 'position_x'],
            },
        ),
        migrations.CreateModel(
            name='UserDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My Dashboard', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('layout_config', models.JSONField(default=dict)),
                ('theme', models.CharField(default='default', max_length=50)),
                ('sidebar_collapsed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_dashboards',
            },
        ),
        migrations.CreateModel(
            name='UserWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.IntegerField(default=0)),
                ('position_y', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=4)),
                ('height', models.IntegerField(default=3)),
                ('is_visible', models.BooleanField(default=True)),
                ('custom_config', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_widgets',
            },
        ),
        migrations.CreateModel(
            name='DashboardActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('view_dashboard', 'View Dashboard'), ('view_student', 'View Student'), ('view_assessment', 'View Assessment'), ('generate_report', 'Generate Report'), ('export_data', 'Export Data'), ('update_settings', 'Update Settings')], max_length=20)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.assessment')),
            ],
            options={
                'db_table': 'dashboard_activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
