# Generated by Django 5.2.5 on 2025-08-24 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardactivity',
            name='related_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='dashboardactivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dashboardnotification',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dashboardnotification',
            name='recipients',
            field=models.ManyToManyField(related_name='dashboard_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dashboardnotification',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_notifications', to='students.school'),
        ),
        migrations.AddField(
            model_name='dashboardsetting',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dashboardwidget',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_widgets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dashboardwidget',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_widgets', to='students.school'),
        ),
        migrations.AddField(
            model_name='userdashboard',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userwidget',
            name='user_dashboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_widgets', to='dashboard.userdashboard'),
        ),
        migrations.AddField(
            model_name='userwidget',
            name='widget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_widget_instances', to='dashboard.dashboardwidget'),
        ),
        migrations.AddField(
            model_name='userdashboard',
            name='widgets',
            field=models.ManyToManyField(related_name='user_dashboards', through='dashboard.UserWidget', to='dashboard.dashboardwidget'),
        ),
        migrations.AlterUniqueTogether(
            name='userwidget',
            unique_together={('user_dashboard', 'widget')},
        ),
    ]
