# Generated by Django 5.2.5 on 2025-08-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('student_performance', 'Student Performance Report'), ('school_performance', 'School Performance Report'), ('assessment_analysis', 'Assessment Analysis Report'), ('wellbeing_report', 'Wellbeing Report'), ('career_guidance', 'Career Guidance Report'), ('risk_assessment', 'Risk Assessment Report')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('report_data', models.JSONField()),
                ('charts_data', models.JSONField(default=dict)),
                ('insights', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'analytics_reports',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_students', models.IntegerField(default=0)),
                ('active_assessments', models.IntegerField(default=0)),
                ('completed_assessments', models.IntegerField(default=0)),
                ('average_performance', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('academic_assessments', models.IntegerField(default=0)),
                ('psychological_assessments', models.IntegerField(default=0)),
                ('physical_assessments', models.IntegerField(default=0)),
                ('dmit_assessments', models.IntegerField(default=0)),
                ('high_performers', models.IntegerField(default=0)),
                ('at_risk_students', models.IntegerField(default=0)),
                ('attendance_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('predictions_generated', models.IntegerField(default=0)),
                ('prediction_accuracy', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dashboard_metrics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trend_type', models.CharField(choices=[('academic', 'Academic Performance'), ('psychological', 'Psychological Wellbeing'), ('physical', 'Physical Health'), ('attendance', 'Attendance'), ('career', 'Career Readiness')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('initial_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('final_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('change_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('trend_direction', models.CharField(max_length=10)),
                ('data_points', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'performance_trends',
                'ordering': ['-end_date'],
            },
        ),
        migrations.CreateModel(
            name='SchoolAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_students', models.IntegerField(default=0)),
                ('active_students', models.IntegerField(default=0)),
                ('new_admissions', models.IntegerField(default=0)),
                ('average_academic_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('academic_performance_distribution', models.JSONField(default=dict)),
                ('subject_performance_summary', models.JSONField(default=dict)),
                ('total_assessments', models.IntegerField(default=0)),
                ('assessment_completion_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('average_assessment_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('average_wellbeing_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('students_at_risk', models.IntegerField(default=0)),
                ('average_attendance_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'school_analytics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StudentAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('academic_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('subject_performance', models.JSONField(default=dict)),
                ('attendance_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('wellbeing_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('stress_level', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('emotional_health', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('fitness_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('physical_activity_level', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('career_readiness', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('learning_style', models.CharField(blank=True, max_length=50, null=True)),
                ('risk_factors', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'student_analytics',
                'ordering': ['-date'],
            },
        ),
    ]
