# Generated by Django 5.2.5 on 2025-08-24 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_analytics', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsreport',
            name='generated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analyticsreport',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='students.school'),
        ),
        migrations.AddField(
            model_name='analyticsreport',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='students.student'),
        ),
        migrations.AddField(
            model_name='dashboardmetrics',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_metrics', to='students.school'),
        ),
        migrations.AddField(
            model_name='performancetrend',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_trends', to='students.student'),
        ),
        migrations.AddField(
            model_name='schoolanalytics',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_analytics', to='students.school'),
        ),
        migrations.AddField(
            model_name='studentanalytics',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_analytics', to='students.student'),
        ),
        migrations.AlterUniqueTogether(
            name='dashboardmetrics',
            unique_together={('school', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='schoolanalytics',
            unique_together={('school', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='studentanalytics',
            unique_together={('student', 'date')},
        ),
    ]
