# Generated by Django 5.2.5 on 2025-08-28 18:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('assessment', 'Assessment'), ('student_support', 'Student Support'), ('communication', 'Communication'), ('administrative', 'Administrative'), ('epr_processing', 'EPR Processing'), ('alert_handling', 'Alert Handling'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('workflow_config', models.JSONField(default=dict, help_text='JSON configuration for workflow steps')),
                ('is_public', models.BooleanField(default=False, help_text='Can be used by other admins')),
                ('max_execution_time', models.IntegerField(default=300, help_text='Maximum execution time in seconds')),
                ('retry_attempts', models.IntegerField(default=3, help_text='Number of retry attempts on failure')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_users', models.ManyToManyField(blank=True, related_name='accessible_workflows', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_workflows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
